// Task 1 //

// Total Taka I Have //
var totalTaka = 1000 ;

// Cost Of 1 KG Of Oranges and 1 KG Of Apples. //
var total_of_oranges_and_apples = 700 ;

// The Money Shopkeeper Will Return //
console.log(totalTaka - total_of_oranges_and_apples);


// Task 2 //


var math = 75.25 ;
var biology = 65 ;
var chemistry = 80 ;
var physics = 35.45 ;
var bangla = 99.50 ;  


var totalMarksInAllSubject = (75.25+65+80+35.45+99.50) ;

var totalSubject = 5 ;

var averageMarks = ( totalMarksInAllSubject / totalSubject) ;

console.log (averageMarks.toFixed(2)) ;

// Task 3 //

var givenNumber = 119 ; 

var divisor = 5 ;

var quotient = ( givenNumber % divisor );

console.log(quotient);
